### ISSUE TITLE
Function return type breaks

### ISSUE THREAD

**Issue by lmajano** [jcberquist/commandbox-cfformat#26] opened 2019-06-19 16:35 UTC
These are my settings:

```json
{
    "brackets.padding": true,
	"strings.quote": "double",
	"strings.attributes.quote": "double",
	"function_call.empty_padding": false,
    "function_call.padding": true,
	"function_declaration.padding": true,
	"function_call.multiline.leading_comma.padding": true,
	"function_declaration.multiline.leading_comma.padding" : true,
	"function_declaration.empty_padding": false,
	"function_declaration.group_to_block_spacing": "compact",
	"struct.padding": true,
	"struct.empty_padding": false,
	"struct.multiline.leading_comma.padding" : true,
	"array.empty_padding":false,
    "array.padding":true,
    "array.multiline.leading_comma.padding":true,
    "binary_operators.padding":true,
    "for_loop_semicolons.padding":true,
    "indent_size":4,
    "parentheses.padding":true,
    "struct.separator":" : ",
	"tab_indent":true,
	"keywords.block_to_keyword_spacing" : "spaced",
	"keywords.group_to_block_spacing" : "spaced",
	"keywords.padding_inside_group" : true,
	"keywords.spacing_to_block" : "compact",
	"keywords.spacing_to_group" : true
}
```

This is current code

```js
/**
* Set form params
* @name The name of the key in the form params
* @value The value
*/
OrtusPDF function setFormParam( required string name, required string value ){
	variables.formparams[ arguments.name ] = arguments.value;
	return this;
}
```

This is the formated code:

```js
/**
* Set form params
* @name The name of the key in the form params
* @value The value
*/
OrtusPDF
function setFormParam( required string name, required string value ){
	variables.formparams[ arguments.name ] = arguments.value;
	return this;
}
```

As you can see it puts the return type of functions in a new line

**Comment by lmajano** [comment] 2019-06-19 16:37
Ok, the setting in question that alters this is `function_declaration.padding`. If you trun it false, then it leaves the return type but does not pad as needed. So it seems its a bug

**Comment by jcberquist** [comment] 2019-06-19 16:57
@lmajano Thanks for the detailed example - I can't reproduce this currently, however, using just the code in the example. Maybe there is an issue in the surrounding context?

**Comment by elpete** [comment] 2020-04-08 16:48
I can't reproduce this either.  @lmajano?

**Comment by jcberquist** [comment] 2020-05-04 18:52
I am closing this issue as I couldn't reproduce.

**Closed by jcberquist** 2020-05-04 18:52 UTC
